### PR TITLE
New sub-module for site featurization and GA model selection

### PR DESCRIPTION
**Pull request by schlexer**

### CODE REVIEW

**Comment by schlexer** [comment]
I wonder if the travis complaints have to do with site_stability at all?

**Comment by mhangaard** [comment]
> I wonder if the travis complaints have to do with site_stability at all?

We had some issues with ASE 3.17.0 using deprecated numpy functions, that caused our tests to crash. Now it seems there are new issues. We should probably drop support for python 2.7, and python 3.5, by changing the `.travis.yml`.

**Comment by schlexer** [comment]
We can definitely drop support for python 2.7, as it [won't be maintained anymore from 2020](https://www.python.org/dev/peps/pep-0373/).
I don't have any strong opinions about 3.5.

**Comment by schlexer** [comment]
I will open an new pull request.

**Pull request closed without merging**
